image: quay.io/poseidon/matchbox:v0.8.3
imagePullPolicy: IfNotPresent

service:
  serviceType: ClusterIP
  loadBalancerIP:

ingress:
  enabled: false

certificate:
  enabled: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - '{{ template "matchbox.fullname" . }}'
  issuerRef:
    name: '{{ template "matchbox.fullname" . }}'
    kind: Issuer

issuer:
  enabled: false

data:
  persistence:
    enabled: false
  volume:
    emptyDir: {}

assets:
  persistence:
    enabled: false
    annotations: {}
  volume:
    emptyDir: {}