image: quay.io/poseidon/matchbox:v0.8.3
imagePullPolicy: IfNotPresent


annotations: {}

labels:
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
  app: '{{ template "matchbox.fullname" . }}'

selectorLabels:
  app: '{{ template "matchbox.fullname" . }}'

httpPort: 8080
rpcPort: 8081

env:
  MATCHBOX_ADDRESS: "0.0.0.0:{{ .Values.httpPort }}"
  MATCHBOX_RPC_ADDRESS: "0.0.0.0:{{ .Values.rpcPort }}"
  MATCHBOX_LOG_LEVEL: "debug"
  MATCHBOX_DATA_PATH: /var/lib/matchbox/data
  MATCHBOX_ASSETS_PATH: /var/lib/matchbox/assets

resources:
  requests:
    cpu: "50m"
    memory: "50Mi"

service:
  serviceType: ClusterIP
  loadBalancerIP:
  http:
    port: 8080
  https:
    port: 8081
  loadBalancerSourceRanges: []

ingress:
  http:
    enabled: false
    path: /
    tls:
      enabled: false
    certificate:
      enabled: false
      annotations: {}
      issuerRef: {}
  https:
    enabled: false
    path: /
    tls:
      enabled: false
    certificate:
      enabled: false
      annotations: {}
      issuerRef: {}

certificate:
  enabled: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - '{{ template "matchbox.fullname" . }}'
  issuerRef:
    name: '{{ template "matchbox.fullname" . }}'
    kind: Issuer

issuer:
  enabled: false

data:
  persistence:
    enabled: false
    accessModes:
      - "ReadWriteOnce"
  volume:
    emptyDir: {}

assets:
  persistence:
    enabled: false
    annotations: {}
    accessModes:
      - "ReadWriteOnce"
  volume:
    emptyDir: {}