{{- if and .Values.assets.persistence.enabled (not .Values.assets.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metaassets:
{{- if .Values.assets.persistence.annotations }}
  annotations:
{{ toYaml .Values.assets.persistence.annotations | indent 4 }}
{{- end }}
  annotations:
  labels:
    app: {{ template "matchbox.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ template "matchbox.fullname" . }}-assets"
spec:
  accessModes:
    - {{ .Values.assets.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.assets.persistence.size | quote }}
{{- if .Values.assets.persistence.storageClass }}
{{- if (eq "-" .Values.assets.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.assets.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
