apiVersion: v1
kind: Service
metadata:
  name: {{ template "matchbox.fullname" . }}
  annotations:
  labels:
    app: {{ template "matchbox.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if (or (eq .Values.service.serviceType "ClusterIP") (empty .Values.service.serviceType)) }}
  type: ClusterIP
{{- else if eq .Values.service.serviceType "LoadBalancer" }}
  type: {{ .Values.service.serviceType }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
{{- else }}
  type: {{ .Values.service.serviceType }}
{{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: "http"
    port: {{ .Values.service.http.port }}
    targetPort: 8080
    {{- if (and (eq .Values.service.serviceType "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  - name: "https"
    port: {{ .Values.service.https.port }}
    targetPort: 8081
    {{- if (and (eq .Values.service.serviceType "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "matchbox.fullname" . }}