apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ template "matchbox.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "matchbox.fullname" . }}
spec:
{{- if (or (eq .Values.matchbox.serviceType "ClusterIP") (empty .Values.matchbox.serviceType)) }}
  type: ClusterIP
{{- else if eq .Values.matchbox.serviceType "LoadBalancer" }}
  type: {{ .Values.matchbox.serviceType }}
  {{- if .Values.matchbox.loadBalancerIP }}
  loadBalancerIP: {{ .Values.matchbox.loadBalancerIP }}
  {{- end }}
  {{- if .Values.matchbox.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.matchbox.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.matchbox.serviceType }}
{{- end }}
  {{- if .Values.matchbox.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.matchbox.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
    {{- if (and (eq .Values.matchbox.serviceType "NodePort") (not (empty .Values.matchbox.nodePort))) }}
    nodePort: {{ .Values.matchbox.nodePort }}
    {{- end }}
  - name: "https"
    port: 8081
    targetPort: 8081
    {{- if (and (eq .Values.matchbox.serviceType "NodePort") (not (empty .Values.matchbox.nodePort))) }}
    nodePort: {{ .Values.matchbox.nodePort }}
    {{- end }}
  selector:
    app: {{ template "matchbox.fullname" . }}